-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2022-11-04 00:23:10.474

-- tables
-- Table: APODERADO
CREATE TABLE APODERADO (
    CODAPOD char(6)  NOT NULL,
    DOCINDAPOD char(8)  NOT NULL,
    NOMAPOD varchar(60)  NOT NULL,
    APEAPOD varchar(60)  NOT NULL,
    CELAPOD char(9)  NOT NULL,
    DIRAPOD varchar(80)  NOT NULL,
    PROAPOD varchar(60)  NOT NULL,
    GMAAPOD varchar(80)  NOT NULL,
    CODEST char(6)  NOT NULL,
    CONSTRAINT APODERADO_pk PRIMARY KEY (CODAPOD)
);

-- Table: ESTUDIANTES
CREATE TABLE ESTUDIANTES (
    CODEST char(6)  NOT NULL,
    DOCINDEST char(8)  NOT NULL,
    NOMEST varchar(60)  NOT NULL,
    APEEST varchar(60)  NOT NULL,
    CELEST char(9)  NOT NULL,
    FECNACEST date  NOT NULL,
    DIREST varchar(70)  NOT NULL,
    PROEST varchar(70)  NOT NULL,
    GMAEST varchar(50)  NOT NULL,
    CODMAT char(10)  NOT NULL,
    CONSTRAINT ESTUDIANTES_pk PRIMARY KEY (CODEST)
);

-- Table: MATRICULA
CREATE TABLE MATRICULA (
    CODMAT char(10)  NOT NULL,
    FECHORMAT time  NOT NULL,
    COSMAT varchar(20)  NOT NULL,
    NUMVACMAT varchar(60)  NOT NULL,
    CODESTU char(10)  NOT NULL,
    GRAMAT char(10)  NOT NULL,
    SECMAT char(10)  NOT NULL,
    CODSEC char(6)  NOT NULL,
    CONSTRAINT MATRICULA_pk PRIMARY KEY (CODMAT)
);

-- Table: SECRETARIO
CREATE TABLE SECRETARIO (
    CODSEC char(6)  NOT NULL,
    NOMSEC varchar(65)  NOT NULL,
    APESEC varchar(60)  NOT NULL,
    CELSEC char(9)  NOT NULL,
    GMASEC varchar(70)  NOT NULL,
    RESSEC varchar(50)  NOT NULL,
    OBSSEC varchar(60)  NOT NULL,
    ORGSEC varchar(60)  NOT NULL,
    CODAPOD char(6)  NOT NULL,
    CONSTRAINT SECRETARIO_pk PRIMARY KEY (CODSEC)
);

-- foreign keys
-- Reference: APODERADO_ESTUDIANTES (table: APODERADO)
ALTER TABLE APODERADO ADD CONSTRAINT APODERADO_ESTUDIANTES
    FOREIGN KEY (CODEST)
    REFERENCES ESTUDIANTES (CODEST)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: MATRICULA_ESTUDIANTES (table: ESTUDIANTES)
ALTER TABLE ESTUDIANTES ADD CONSTRAINT MATRICULA_ESTUDIANTES
    FOREIGN KEY (CODMAT)
    REFERENCES MATRICULA (CODMAT)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: SECRETARIO_APODERADO (table: SECRETARIO)
ALTER TABLE SECRETARIO ADD CONSTRAINT SECRETARIO_APODERADO
    FOREIGN KEY (CODAPOD)
    REFERENCES APODERADO (CODAPOD)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: SECRETARIO_MATRICULA (table: MATRICULA)
ALTER TABLE MATRICULA ADD CONSTRAINT SECRETARIO_MATRICULA
    FOREIGN KEY (CODSEC)
    REFERENCES SECRETARIO (CODSEC)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- End of file.

